#!/usr/bin/env python3

import re
import subprocess
from testlib import *
    
# test the first thread task: add locks to eliminate the missing keys.
@test(10, "thr_safe")
def test_ph_safe():
    subprocess.run(['make', 'thr'], check=True)
    result = subprocess.run(['./thr', '2'], stdout=subprocess.PIPE, check=True)
    out = result.stdout.decode("utf-8")
    matches = re.findall(r'^\d+: (\d+) keys missing$', out, re.MULTILINE)
    assert_equal(len(matches), 2)
    assert_equal(int(matches[0]), 0)
    assert_equal(int(matches[1]), 0)

run_tests()

